### UserSample - /login
POST {{hosts}}/login
Accept-Language: en
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId2a",
  "password": "1234!"
}

> {%
client.global.set("access_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
client.log("Bearer " + client.global.get("access_token"));
client.log("Bearer " + client.global.get("refresh_token"));
%}

### UserSample - /login
GET {{hosts}}/login
Authorization: Bearer {{access_token}}

### UserSample - /refresh
POST {{hosts}}/refresh
Authorization: Bearer {{refresh_token}}

> {%
client.global.set("access_token", response.body.access_token);
client.log("Bearer " + client.global.get("access_token"));
%}

### UserSample - /refresh
GET {{hosts}}/refresh
Authorization: Bearer {{refresh_token}}

### UserSample - /user
GET {{hosts}}/user
    ?start_row=0
    &row_per_page=10
Authorization: Bearer {{access_token}}

### UserSample - /user
POST {{hosts}}/user
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId6",
  "password": "1234!",
  "user_name": "사용자6"
}

### UserSample - /user/<int:user_seq>
GET {{hosts}}/user/2
Authorization: Bearer {{access_token}}

### UserSample - /user/<int:user_seq>
PUT {{hosts}}/user/3
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId2",
  "password": "1234!",
  "user_name": "사용자2 수정1"
}

### UserSample - /user/<int:user_seq>
DELETE {{hosts}}/user/2
Authorization: Bearer {{access_token}}

### BoardSample - /board
GET {{hosts}}/board
    ?start_row=0
    &row_per_page=5
# optional=True
Authorization: Bearer {{access_token}}

### BoardSample - /board
POST {{hosts}}/board
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "title": "제목",
  "contents": "내용"
}

### BoardSample - /board/<int:board_seq>
GET {{hosts}}/board/4

### BoardSample - /board/<int:board_seq>
PUT {{hosts}}/board/5
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "title": "제목3",
  "contents": "내용3"
}

### BoardSample - /board/<int:board_seq>
DELETE {{hosts}}/board/2
Authorization: Bearer {{access_token}}

### BoardSample - /board/fileupload
# 테스트 시 한글 파일명이 깨지는 현상이 있어 filename 설정은 영어로 설정
# 파일업로드를 브라우저에서 할 경우 한글 파일명이 깨지지 않음
POST {{hosts}}/board/fileupload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name=file; filename="sample.xlsx"

< ../../../../Downloads/한글 파일명 (1).xlsx
--boundary--

### BoardSample - /board/<int:board_seq>/file
POST {{hosts}}/board/2/file
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId",
  "file_list": [
    {
      "file_seq": "",
      "file_org_name": "sample.xlsx",
      "file_tmp_path": "tmp",
      "file_tmp_name": "621c2a4d6df04cc2a985de0ddcf311b2.xlsx"
    },
    {
      "file_seq": "",
      "file_org_name": "sample.xlsx",
      "file_tmp_path": "tmp",
      "file_tmp_name": "aa4a94f9a08d43f48d5b2eda1c3af37a.xlsx"
    },
    {
      "file_seq": "",
      "file_org_name": "sample.xlsx",
      "file_tmp_path": "tmp",
      "file_tmp_name": "0a2a39bb5e2745e993abd080abc14f71.xlsx"
    },
    {
      "file_seq": "",
      "file_org_name": "sample.xlsx",
      "file_tmp_path": "tmp",
      "file_tmp_name": "d13e28396203410a98fdaf4a417370a1.xlsx"
    }
  ]
}

### BoardSample - /board/<int:board_seq>/file
GET {{hosts}}/board/1/file
