### UserSample - /login
POST {{hosts}}/login
Accept-Language: ja
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId3",
  "password": "1234!"
}

> {%
client.global.set("access_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
client.log("Bearer " + client.global.get("access_token"));
client.log("Bearer " + client.global.get("refresh_token"));
%}

### UserSample - /login
GET {{hosts}}/login
Authorization: Bearer {{access_token}}

### UserSample - /refresh
POST {{hosts}}/refresh
Authorization: Bearer {{refresh_token}}

> {%
client.global.set("access_token", response.body.access_token);
client.log("Bearer " + client.global.get("access_token"));
%}

### UserSample - /refresh
GET {{hosts}}/refresh
Authorization: Bearer {{refresh_token}}

### UserSample - /user
GET {{hosts}}/user
    ?start_row=0
    &row_per_page=10
Authorization: Bearer {{access_token}}

### UserSample - /user/auth_code/<auth_code:auth_code>
GET {{hosts}}/user/auth_code/USER
    ?start_row=0
    &row_per_page=10
Authorization: Bearer {{access_token}}

### UserSample - /user/user_seqs/<int_list:user_seqs>
GET {{hosts}}/user/user_seqs/1,4,5
Authorization: Bearer {{access_token}}

### UserSample - /user/user_seqs/<int_list:user_seqs>
DELETE {{hosts}}/user/user_seqs/2,3
Authorization: Bearer {{access_token}}

### UserSample - /user
POST {{hosts}}/user
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId7",
  "password": "1234!",
  "user_name": "사용자7",
  "auth_code": "USER"
}

### UserSample - /user/<int:user_seq>
GET {{hosts}}/user/2
Authorization: Bearer {{access_token}}

### UserSample - /user/<int:user_seq>
PUT {{hosts}}/user/3
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "user_id": "UserId2",
  "password": "1234!",
  "user_name": "사용자2 수정1",
  "auth_code": "USER"
}

### UserSample - /user/<int:user_seq>
DELETE {{hosts}}/user/2
Authorization: Bearer {{access_token}}

### BoardSample - /board
GET {{hosts}}/board
    ?start_row=0
    &row_per_page=5
# optional=True
Authorization: Bearer {{access_token}}

### BoardSample - /board/<boards_code:boards_code>
GET {{hosts}}/board/POST
    ?start_row=0
    &row_per_page=5
# optional=True
Authorization: Bearer {{access_token}}

### BoardSample - /board/boards_code/<boards_code:boards_code>
GET {{hosts}}/board/POST
    ?start_row=0
    &row_per_page=5
# optional=True
Authorization: Bearer {{access_token}}

### BoardSample - /board/board_seqs/<int_list:board_seqs>
GET {{hosts}}/board/board_seqs/10,11,12,13
# optional=True
Authorization: Bearer {{access_token}}

### BoardSample - /board/board_seqs/<int_list:board_seqs>
DELETE {{hosts}}/board/board_seqs/11,12
Authorization: Bearer {{access_token}}

### BoardSample - /board
POST {{hosts}}/board
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "boards_code": "POST",
  "title": "제목",
  "contents": "내용",
  "add_fields": {
    "a_str": "문자열",
    "b_int": 1234,
    "c_float": 12.34,
    "d_list_str": ["문자1", "문자2", "문자3"]
  }
}

### BoardSample - /board
POST {{hosts}}/board
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "boards_code": "POST",
  "title": "제목",
  "contents": "내용",
  "add_fields": {}
}

### BoardSample - /board
# add_fields 의 내용이 모델과 일치하지 않아도 데이터 저장은되지만, 상세보기에서는 key 패턴 매핑이 되지 않아 데이터가 조회되지 않음
POST {{hosts}}/board
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "boards_code": "POST",
  "title": "제목",
  "contents": "내용",
  "add_fields": {
    "a": "a",
    "b": "b",
    "c": 1
  }
}

### BoardSample - /board/<int:board_seq>
GET {{hosts}}/board/8
# optional=True
Authorization: Bearer {{access_token}}

### BoardSample - /board/<int:board_seq>
PUT {{hosts}}/board/8
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "boards_code": "POST",
  "title": "제목4",
  "contents": "내용4",
  "add_fields": {
    "a_str": "문자열4",
    "b_int": 12345,
    "c_float": 12.345,
    "d_list_str": ["문자1", "문자2", "문자3", "문자4"]
  }
}

### BoardSample - /board/<int:board_seq>
DELETE {{hosts}}/board/6
Authorization: Bearer {{access_token}}

### BoardSample - /board/fileupload
# 테스트 시 한글 파일명이 깨지는 현상이 있어 filename 설정은 영어로 설정
# 파일업로드를 브라우저에서 할 경우 한글 파일명이 깨지지 않음
POST {{hosts}}/board/fileupload
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name=file; filename="README.md"

< ../README.md
--boundary
Content-Disposition: form-data; name=file; filename="README.md"

< ../README.md
--boundary--

### BoardSample - /board/<int:board_seq>/file
POST {{hosts}}/board/4/file
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8

{
  "file_list": [
    {
      "file_seq": "",
      "file_org_name": "README.md",
      "file_tmp_path": "tmp",
      "file_tmp_name": "e881345fceaa40e2b03414c92188c3bf.md"
    },
    {
      "file_seq": "",
      "file_org_name": "README.md",
      "file_tmp_path": "tmp",
      "file_tmp_name": "2860ed1f78ab4edfac6bcc4083820ca8.md"
    }
  ]
}

### BoardSample - /board/<int:board_seq>/file
GET {{hosts}}/board/4/file
Authorization: Bearer {{access_token}}
